#!/usr/bin/php
<?php
/**
 * service
 *
 * Configure commands to run and easily run them. Mimiced after RedHat's service
 * command.
 *
 * @version    $Id:$
 * @link       https://github.com/jmleapline/Random-Scripts
 */

// GLOBAL VARIBLES
global $OPTION;
$OPTION['list'] = FALSE;
$DEBUG = FALSE;
$args = "";

// configuration JSON file // looks in PWD
$configFile = json_decode(file_get_contents('commands.json', FILE_USE_INCLUDE_PATH));

/**
 * function / parseArgs
 *
 * Need to parse the arguments passed through the command line
 *
 * @param null
 *
 * @return null
 */
function parseArgs()
{
    // Globals
    global $OPTION;
    $argv = $GLOBALS["argv"];
    $args = &$GLOBALS["args"];
    $count = 0; // the count for the non-option arguments.
    
    // See what has been passed and get them recorded.
    while (($param = array_shift($argv)) !== NULL) {
        switch ( $param ) {
            case '-h':
                printHelp();
                break;
            case '-a':
            case '--args':
                $args = array_shift($argv);
                break;
            case '--list':
                $OPTION['list'] = TRUE;
                break;
            default:
            	$OPTION[$count] = $param;
            	$count++;
            	break;
        }
    }
    
    $OPTION['service'] = (isset($OPTION[1]) ? $OPTION[1] : null);
    $OPTION['command'] = (isset($OPTION[2]) ? $OPTION[2] : null);

}

/**
 * function / printHelp
 *
 * print some help messages
 *
 * @param null
 *
 */
function printHelp()
{
    // Print message
    print <<<EOT

service <service> <command>
The script automates running, starting, and stoping different services.

Typical commands are
	start : start the service
	stop : stop the service
	restart : restart the service
	list : list all the available services / commands


EOT;

    exit;
}


/**
 * function / execute
 *
 * execute the said command(s)
 *
 * @param string $command
 *
 */
function execute($command)
{
    global $OPTION, $configFile, $args;
    
    if ( !is_array($command) )
        $command = array($command);
        
    // if the command is actually an array of commands, run them all
    foreach ($command as $key => $run) {
        // if we are passing an argument
        if ( !empty($args) )
            $run = str_replace("%args%", $args, $run);
        
        if ($configFile->$OPTION['service']->admin)
            passthru("sudo " . $run, $cmdError);
        else
            passthru($run, $cmdError);

        printStatus($run, $cmdError);;    
    }
    
    exit;
}


/**
 * function / printStatus
 *
 * print the status of the command run - debug if necessary
 *
 * @param string $command
 * @param string $cmdOutput
 * @param string $cmdError
 *
 * @return string $color
 *
 */
function printStatus($command, $cmdError)
{

    if ($cmdError == 0)
        print set("[+]", "green") . " " . $command . "\n";
    else
        print set("[-]", "red") . " " . $command . "\n";

}

/**
 * function / listCMDs
 *
 * list out the available commands for the said service
 *
 * @param string $service
 *
 * @return null
 *
 */
function listCMDs($service)
{
    global $OPTION, $configFile;

    print "Command options for " . set($service, "blue") . "\n\n";
    foreach ($configFile->$service->commands as $key => $value) {
        // if the value is an array, print out each one
        if (is_array($value)) {
            foreach ($value as $item)
                print "    " . set($key, "green") . " (" . set("multi", "bold+yellow") . ")" . " : $item\n";
        } else {
            print "    " . set($key, "green") . " : $value\n";
        }
    }

    print "\n";
    exit;

}

/**
 * function / set
 *
 * Thanks to php-ansi-color (https://github.com/loopj/commonjs-ansi-color).
 * This sets the color on the terninal if you have ncurses.
 *
 * @param string $str
 *
 * @return string $color
 */
function set($str, $color)
{
	static $ANSI_CODES = array(
		"off"        => 0,
		"bold"       => 1,
		"italic"     => 3,
		"underline"  => 4,
		"blink"      => 5,
		"inverse"    => 7,
		"hidden"     => 8,
		"black"      => 30,
		"red"        => 31,
		"green"      => 32,
		"yellow"     => 33,
		"blue"       => 34,
		"magenta"    => 35,
		"cyan"       => 36,
		"white"      => 37,
		"black_bg"   => 40,
		"red_bg"     => 41,
		"green_bg"   => 42,
		"yellow_bg"  => 43,
		"blue_bg"    => 44,
		"magenta_bg" => 45,
		"cyan_bg"    => 46,
		"white_bg"   => 47
	);
	$color_attrs = explode("+", $color);
	$ansi_str = "";
	foreach ($color_attrs as $attr) {
		$ansi_str .= "\033[" . $ANSI_CODES[$attr] . "m";
	}
	$ansi_str .= $str . "\033[" . $ANSI_CODES["off"] . "m";
	return $ansi_str;
}

/**
 * function / isRunning
 *
 * Check to see if the process is running.
 *
 * @param string $process
 *
 * @return null
 */
function isRunning( $process ) {
    
    if ( !is_array($process) )
        $process = array($process);
        
    // if the command is actually an array of commands, run them all
    foreach ($process as $processStr) {
    
        exec( 'pgrep '. $processStr, $null, $returnVal );
                
        if ( $returnVal == 0 )
            print set("[+]", "green") . " " . set($processStr, "bold") . " is running\n";
        else
            print set("[-]", "red") . " " . set($processStr, "bold") . " is stopped\n";
        
    }    
} 


///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////


// Parse the arguments
///////////////////////////////////////////////////////////////////////////////////////
parseArgs();

// Check to see if we need to list out all the commands available

///////////////////////////////////////////////////////////////////////////////////////
// if need to list out commands
if ( $OPTION['list'] && empty( $OPTION['service'] ) ) {
    print "All the services available\n\n";

    foreach ($configFile as $key => $value) {
        print "    " . set($key, "blue") . "\n";
    }

    print "\n";
    print "Run " . set("service <service> list", "green") . " for more command options.\n";
    exit;
}

///////////////////////////////////////////////////////////////////////////////////////
// check to see if the command exists
if ( empty( $OPTION['service'] ) || !isset( $OPTION['service'] ) ) {
    print set("[-]", "red") . " " . set("service is not defined", "red_bg") . "\n";
    exit;
}

///////////////////////////////////////////////////////////////////////////////////////
// check to see if we have list set with the service
if ( $OPTION['list'] ) {
    listCMDs($OPTION['service']);
    exit;
}
    
///////////////////////////////////////////////////////////////////////////////////////
// if there is nothing set for command and there is a default set, run that.
if ( !isset($OPTION['command']) && isset($configFile->$OPTION['service']->default) ) {
    
    // check to see if the command exists (configuration issue)
    if (isset($configFile->$OPTION['service']->commands->{$configFile->$OPTION['service']->default}))
        execute($configFile->$OPTION['service']->commands->{$configFile->$OPTION['service']->default});
        
}

///////////////////////////////////////////////////////////////////////////////////////
// check to see if the command exists, and run it
if ( isset($configFile->$OPTION['service']->commands->$OPTION['command']) ) {
    
    // special case for the status command
    if ( $OPTION['command'] == 'status' ) {
        isRunning( $configFile->$OPTION['service']->commands->$OPTION['command'] );
    } else {
        execute($configFile->$OPTION['service']->commands->$OPTION['command']);
    }
    
} else {
    print set("[-]", "red") . " " . set("command is not defined", "red_bg") . "\n";
}


/*-----------------------------------------------------------------------------*/
?>